spring.application.name=ViajeSeguroSpringBoot

#CONFIGURACION A LA BD DE MYSQL

spring.datasource.url=jdbc:mysql://localhost:3306/bd_ViajeSeguro
spring.datasource.username=root
spring.datasource.password=

#Determinar el driver mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Configuraciones importantes
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#importante open-in-view
spring.jpa.open-in-view=false
